if (NOT MINGW_ARCH)
    set(MINGW_ARCH x86_64)
endif ()

if (NOT MINGW_TRIPLE)
    set(MINGW_TRIPLE x86_64-w64-mingw32)
endif ()

if (NOT MINGW_PREFIX)
    set(MINGW_PREFIX /usr/${MINGW_TRIPLE})
endif ()

if (NOT MINGW_CC)
    set(MINGW_CC gcc)
endif ()

if (MINGW_CC STREQUAL "gcc")
    set(MINGW_CXX g++)
else ()
    set(MINGW_CXX ${MINGW_CC}++)
endif ()

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR ${MINGW_ARCH})

set(CMAKE_C_COMPILER ${MINGW_TRIPLE}-${MINGW_CC})
set(CMAKE_CXX_COMPILER ${MINGW_TRIPLE}-${MINGW_CXX})
set(CMAKE_RC_COMPILER ${MINGW_TRIPLE}-windres)
set(CMAKE_STRIP ${MINGW_TRIPLE}-strip)

set(CMAKE_FIND_ROOT_PATH ${MINGW_PREFIX})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
