name: Build OpenWrt eSurfingClient

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main, master ]
    paths: [ '**' ]  # 任何文件变更都会触发
  pull_request:
    branches: [ main, master ]

env:
  SDK_FILENAME: "openwrt-sdk-21.02.7-ramips-mt7621_gcc-8.4.0_musl.Linux-x86_64.tar.xz"

jobs:
  build-mipsel-openwrt:
    runs-on: ubuntu-20.04  # 使用较旧的Ubuntu版本以确保兼容性
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup environment and install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          clang \
          flex \
          bison \
          g++ \
          gawk \
          gcc-multilib \
          g++-multilib \
          gettext \
          git \
          libncurses5-dev \
          libssl-dev \
          python3-distutils \
          rsync \
          wget \
          xz-utils \
          file

    - name: Make script executable
      run: chmod +x build-mipsel_24kc-openwrt_21.02.7.sh

    - name: Create necessary directories and files
      run: |
        # 确保所需的目录和文件存在
        mkdir -p esurfingclient
        if [ ! -f "menuconfig.config" ]; then
          echo "Warning: menuconfig.config not found, creating empty one"
          touch menuconfig.config
        fi
        if [ ! -d "esurfing" ]; then
          echo "Warning: esurfing directory not found, creating empty one"
          mkdir -p esurfing
          echo "This is a placeholder for esurfing package" > esurfing/README
        fi

    - name: Run build script
      run: ./build-mipsel_24kc-openwrt_21.02.7.sh
      env:
        DEBIAN_FRONTEND: noninteractive

    - name: Upload built package
      uses: actions/upload-artifact@v4
      with:
        name: esurfingclient-package
        path: esurfingclient-mipsel_24kc-openwrt-21.02.7-1.0.0.ipk
        retention-days: 30

    - name: Upload build logs (if any)
      if: always()  # 即使构建失败也上传日志
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          openwrt-sdk/logs/
          openwrt-sdk/**/*.log
        retention-days: 7
